title: "❓ [Question]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        ## Ask a Question
        Have a question about TeachLink? Ask away! Please check existing Q&A first.

  - type: checkboxes
    id: search
    attributes:
      label: Before asking
      options:
        - label: I have searched existing discussions and issues
          required: true
        - label: I have checked the documentation
          required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm wondering about...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      options:
        - Getting Started
        - Smart Contracts
        - Deployment
        - Testing
        - Contributing
        - Architecture
        - Token/Rewards
        - Bridge
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant context or what you've already tried
      placeholder: I've already tried...
