name: ✨ Feature Request
description: Suggest a new feature or enhancement for TeachLink
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature! Please fill out the sections below.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues/discussions to ensure this feature hasn't been requested
          required: true
        - label: I have read the project [ROADMAP](https://github.com/rinafcode/teachLink_contract/blob/main/docs/governance/ROADMAP.md)
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New Contract Functionality"
        - "Contract Enhancement"
        - "Developer Experience (DX)"
        - "Documentation"
        - "Testing/Quality"
        - "Tooling/Scripts"
        - "Integration/Bridge"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any API changes, new functions, or modifications needed.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority Assessment
      description: How important is this feature to you?
      options:
        - "Critical - Blocker for adoption"
        - "High - Significantly improves experience"
        - "Medium - Nice to have"
        - "Low - Minor improvement"
    validations:
      required: true

  - type: dropdown
    id: affected_contract
    attributes:
      label: Affected Component
      description: Which component would this feature affect?
      options:
        - TeachLink (main contract)
        - Insurance module
        - Bridge module
        - Escrow module
        - Scripts/Tooling
        - Documentation
        - Multiple/All
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be valuable
      placeholder: |
        As a [type of user], I want to [do something], so that [benefit]...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: |
        Technical details, pseudocode, or references to similar implementations...

  - type: textarea
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature require any breaking changes?
      placeholder: List any potential breaking changes to existing APIs or behaviors

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      options:
        - label: I would be willing to submit a PR implementing this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature
