[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "panic=abort",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--max-memory=4294967296",
]
